# Generated by Django 2.2.4 on 2019-08-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('EmailIsVerified', models.BooleanField()),
                ('InformationsForFB', models.TextField()),
                ('InformationsForGoogle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('Batch_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Batch_Received_DateTime', models.DateTimeField()),
                ('Batch_Version', models.IntegerField()),
                ('Project_Name', models.CharField(max_length=255)),
                ('Project_Description', models.TextField()),
                ('Project_IsPublic', models.BooleanField()),
                ('Project_FileSourcePathName', models.CharField(max_length=255)),
                ('AnalysisSource_ColumnsNameInput', models.TextField()),
                ('AnalysisSource_ColumnsNameOutput', models.TextField()),
                ('AnalysisSource_ColumnType', models.TextField()),
                ('AnalysisSource_CountLinesForTraining', models.TextField()),
                ('AnalysisSource_CountLinesForPrediction', models.TextField()),
                ('AnalysisSource_Errors', models.TextField()),
                ('AnalysisSource_Warnings', models.TextField()),
                ('ParameterCNN_Loss', models.TextField()),
                ('ParameterCNN_Optimizer', models.TextField()),
                ('ParameterCNN_Shape', models.TextField()),
                ('Solving_DateTimeSending', models.DateTimeField()),
                ('Solving_CSVSolvedMergedFilePath', models.CharField(max_length=255)),
                ('Solving_DelayElapsed', models.IntegerField()),
                ('Solving_Acuracy', models.BooleanField()),
                ('Solving_TextError', models.TextField()),
                ('Solving_TextWarning', models.TextField()),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.User')),
            ],
        ),
    ]
