# Generated by Django 2.2.4 on 2019-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20190802_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_ColumnType',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_ColumnsNameInput',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_ColumnsNameOutput',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_CountLinesForPrediction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_CountLinesForTraining',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_Errors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='AnalysisSource_Warnings',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Batch_Received_DateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Batch_Version',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ParameterCNN_Loss',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ParameterCNN_Optimizer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ParameterCNN_Shape',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Project_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Project_FileSourcePathName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Project_IsPublic',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Project_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Solving_Acuracy',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Solving_CSVSolvedMergedFilePath',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Solving_DateTimeSending',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Solving_DelayElapsed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Solving_TextError',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Solving_TextWarning',
            field=models.TextField(null=True),
        ),
    ]
