# Generated by Django 2.2.4 on 2019-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_auto_20190802_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Project_FileSourcePathName',
            field=models.FileField(default=True, upload_to='uploads'),
        ),
    ]
